packages:
  - "apps/*"
  - "packages/*"
  - "packages/config/*"

catalog:
  # Runtime
  typescript: ^5.7.3
  "@nestjs/core": ^11.0.0
  "@nestjs/common": ^11.0.0
  "@nestjs/platform-express": ^11.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.1.0
  "@mantine/core": ^7.17.0
  "@mantine/hooks": ^7.17.0
  prisma: ^6.3.0
  "@prisma/client": ^6.3.0

  # Build
  vite: ^6.1.0
  "@vitejs/plugin-react-swc": ^4.1.0
  "@swc/cli": ^0.6.0
  "@swc/core": ^1.10.0
  "@nestjs/schematics": ^11.0.0
  "@nestjs/cli": ^11.0.0

  # Linting
  eslint: ^9.19.0
  typescript-eslint: ^8.24.0

  # Testing
  vitest: ^3.0.0

  # Tailwind
  tailwindcss: ^4.0.0
  "@tailwindcss/vite": ^4.0.0
