export type {
  Household,
  HouseholdMember,
  Pet,
  RoutineTemplate,
  DailyChecklistItem,
  ActivityLog,
  WeightEntry,
  VetVisit,
  Vaccination,
  Medication,
  TrainingMilestone,
  ActivityType,
  TrainingStatus,
  MedicationFrequency,
} from "@personal-os/database";
export type {
  CreateHouseholdInput,
  UpdateHouseholdInput,
  AddHouseholdMemberInput,
  CreatePetInput,
  UpdatePetInput,
  CreateRoutineTemplateInput,
  UpdateRoutineTemplateInput,
  CreateActivityLogInput,
  CreateWeightEntryInput,
  CreateVetVisitInput,
  UpdateVetVisitInput,
  CreateVaccinationInput,
  UpdateVaccinationInput,
  CreateMedicationInput,
  UpdateMedicationInput,
  CreateTrainingMilestoneInput,
  UpdateTrainingMilestoneInput,
} from "./types.ts";
export {
  HOUSEHOLD_NAME_MAX_LENGTH,
  PET_NAME_MAX_LENGTH,
  PET_BREED_MAX_LENGTH,
  ROUTINE_NAME_MAX_LENGTH,
  ACTIVITY_NOTE_MAX_LENGTH,
  VET_REASON_MAX_LENGTH,
  VET_NOTES_MAX_LENGTH,
  VACCINE_NAME_MAX_LENGTH,
  MED_NAME_MAX_LENGTH,
  MED_DOSAGE_MAX_LENGTH,
  MED_NOTES_MAX_LENGTH,
  TRAINING_COMMAND_MAX_LENGTH,
  TRAINING_NOTES_MAX_LENGTH,
  MAX_HOUSEHOLD_MEMBERS,
  ACTIVITY_TYPES,
  TRAINING_STATUSES,
  MEDICATION_FREQUENCIES,
} from "./constants.ts";
export {
  validateCreateHousehold,
  validateUpdateHousehold,
  validateAddHouseholdMember,
  validateCreatePet,
  validateUpdatePet,
  validateCreateRoutineTemplate,
  validateUpdateRoutineTemplate,
  validateCreateActivityLog,
  validateCreateWeightEntry,
  validateCreateVetVisit,
  validateUpdateVetVisit,
  validateCreateVaccination,
  validateUpdateVaccination,
  validateCreateMedication,
  validateUpdateMedication,
  validateCreateTrainingMilestone,
  validateUpdateTrainingMilestone,
} from "./validation.ts";
export {
  computePetAge,
  computeGrowthStage,
  computeTrainingProgress,
  computeTimeSince,
} from "./computations.ts";
